### ISSUE TITLE
0xf754c8fe:0x1b Smoke Puff

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#107]
Packet 0xf754c8fe JamCRC("simpleEvent") (server to client)
Subtype 0x1b (purpose unknown)
ObjectID (int) ObjectID of a player ship
UnknownA (int) values of 0..7 seen, doesn't seem to be Ship Index, might be ship system or something?
X (float), Y (float), Z (float) - big assumptions here. Low-ish, definitely not galactic coords but maybe ship coords? Place where ship has been damaged?
Usually comes before a DamageShake() which you call PlayerShipDamagePacket

Definitely still WIP  :-(

**Comment by NoseyNick** [comment]
Over 20,000 recorded in the wild

Theory: Damage to a particular location of the ship, or the sparkle on the shields

Values for UnknownA are still 0..7 but still really unlikely to be a Ship Index (much too evenly spread, should be MUCH more heavily biassed towards 0,1(,2) if it was a Ship Index)
Values for (assumed) X are -100 to +100, except when they are 23000 to 38000 (GRR)
Values for (assumed) Y are -50 to +60
Values for (assumed) Z are -165 to +122, except when they are 46000 to 57000 (GRRR)

Still WIP   :confused:

**Comment by NoseyNick** [comment]
It's the smoke puff!

Packet 0xf754c8fe JamCRC("simpleEvent") - server to client
Subtype 0x1b Smoke Puff
ObjectID (int) ObjectID of a player ship
Unknown (int) values of 0..7 seen, doesn't seem to be duration, doesn't seem to be Ship Index, might be "ship system which is on fire", might be "smoke puff type"? Anecdotally, lower numbers seem to be regarded as more important, and make the client ignore higher numbers?
X (float), Y (float), Z (float) - ship coords (-100..+100, -50..+60, -165..+125)
... except some extreme "ship coords" have been seen that look more like galactic coords - might be a bug, or might be smoke left behind after an object has been destroyed

Visible on the DISCO server for the next few days/weeks - connect your v2.7.0 client to noseynick.org

**Comment by NoseyNick** [comment]
"help wanted" if someone wants to figure out the Unknown, otherwise I think this is "ready for update", certainly better than being undocumented   :grinning:

**Comment by JordanLongstaff** [comment]
I'm posting a log from a test I performed parsing smoke packets. The number on the end of each line is the "unknown" value. This was me taking a steady diet of direct fire until I got destroyed. I got to a point where I could full stop and just take hits in the same location, and the same location kept smoking every time. I feel like ruling out "smoke puff type" as an option because despite the random-ish number set, the smoke puffs all generally looked the same to me on the main screen. I also feel like ruling out "ship system type" because I quickly got to the point where it was all hallway sections being destroyed bit by bit, yet the numbers are still wildly spread out. In fact, when you get to the more consistent part of the data in terms of coordinates, you still see wildly different numbers.
[smokelog1.txt](https://github.com/artemis-nerds/protocol-docs/files/2475105/smokelog1.txt)

**Comment by NoseyNick** [comment]
"Anecdotally, lower numbers seem to be regarded as more important, and make the client ignore higher numbers" - might be like a "priority", and the rendering engine ignores higher values if lower values are taking priority? I THINK when I deliberately had lower "Unknown" on the LHS and higher on the RHS of the ship, it looked like it was only smoking on one side even though it was supposed to be all over.

**Comment by NoseyNick** [comment]
Connect a 2.7.1 client to noseynick.net - my disco server - and click "ready to play". This is not a real server, it ignores all commands you send to it, but it sends enough packets to render a ship, some flashy lights, some flashy nebulae, a detonating mine, oh and a bunch of very annoying sound effects   :-D
It's sending low-"unknown" puffs on the LHS of the ship, and high-"unknown" puffs on the RHS (in fact, "unknown" is proportional to X). You probably can't see any on the RHS, can you? I think the low values of "unknown" are hiding / overriding the higher values.

**Comment by NoseyNick** [comment]
Source code at: http://noseynick.net/artemis/disco-server.pl
Requires parser.pl (which is being used as the opposite of a parser here, but never mind)

        my $type = rand(8);
        SmokePuff(1000,  int($type),  10.0*$type-40.0, rand(80)-40, rand(80)-40);

... and if you capture the packets, you'll find X is indeed all the way from -40 to +40, but you can only see the -40 to maybe -10 ones, corresponding to $type=0 to 3 ish. If I run the same but with...

        SmokePuff(1000,  0,  10.0*$type-40.0, rand(80)-40, rand(80)-40);

... you'll see them spread across the whole width of the ship, all have "unknown"==0.

**Comment by JordanLongstaff** [comment]
Well, testing to the exact specs you suggest, yes, I can only see smoke on the left side and nothing on the right. However, I then tried modifying my proxy server to increase the unknown value on SmokePackets by 1 (mod 8), expecting to see only smoke on the RHS (where 7s are, according to you), and instead I see them all over.

**Comment by JordanLongstaff** [comment]
What in the world would it mean for smoke packets to require a "priority" value? Is this only used to prevent too much smoke from showing all at once? Perhaps Thom put a cap on the size of the "drawn object queue" and uses this "priority" field as a means of choosing which smoke puffs to draw if there are too many. This would potentially carry various game-related implications such as memory usage reduction and/or frame rate stabilization.

**Comment by JordanLongstaff** [comment]
After further testing, I found something interesting. I tried a test where I created eight smoke puffs simultaneously in a horizontal line, all with the same unknown value, and only the last of these puffs actually manifested for a lengthy amount of time (others appeared but only extremely briefly). This was true regardless of the unknown values, just as long as they were all the same between the eight packets. This says to me that yes, there is some kind of buffering mechanic that is being used, but not only that, only up to eight smoke puffs (actually, probably even fewer with the possibility of this priority function that could also be there) can appear on screen at any one time and the only way multiple smoke puffs can appear is if they each have different values in this slot.

**Comment by JordanLongstaff** [comment]
It looks like this "priority" meaning still does apply to this unknown value, however, because I just did a test where I saw two smoke puffs next to each other with consecutive values (e.g. 4 and 5, or 7 and 0) and the one with the lower value always appeared bigger than the other one, until it disappeared and then the smaller puff became bigger. Then my test created another smoke puff with the next unknown value in the cycle, and this new puff appeared smaller than the older one on screen, until that puff disappeared and the one that was left became bigger. Occasionally, I saw three puffs on screen at the same time during this test because the next one in line appeared slightly early, and the third puff looked no bigger than a mere wisp until the biggest puff disappeared, then both of the remaining two puffs got bigger. But invariably, the lower the unknown value a particular puff had in comparison to any other smoke puffs, the bigger it appeared. So I think this value represents an index of the "smoke size queue" where smaller indexed puffs appear bigger than larger indexed ones, but only have their puff size reduced if another puff exists with a smaller index; otherwise they're as big as possible, but also any new smoke puff deletes any pre-existing smoke puff with the same index.

**Comment by NoseyNick** [comment]
Re-opening this as we seem to be exploring in a lot more detail than before. Met @JordanLongstaff yesterday evening and did a bit more hacking. I'm going to have the disco-server send a few pre-written sequences I think, but current working theory:
* "Unknown" is "slot", for lack of a better word:
* There are 8 slots / array entries for smoke puffs, 0-7.
* Sending another puff with the same "slot" will overwrite the previous one - the previous smoke will stop and the new one will start (at new coords or whatever)
* Smoke will expire after some time (have we counted the seconds?)
* The first non-expired puff in the array is big
* The second non-expired puff in the array is medium-sized
* The third non-expired puff in the array is small
* Other non-expired puffs are probably not seen at all unless they are still around after lower-slotted puffs expire

Sound about right, @JordanLongstaff ?

**Comment by JordanLongstaff** [comment]
Sounds _about_ right. I submitted a pull request (referenced above) that gives it the name "Priority" because that was the name you originally gave it and it's honestly not too far off.

**Comment by NoseyNick** [comment]
Essentially fixed by PR #176 - closing this sisue. Feel free to re-open if anyone thinks there's more detail required.
