### ISSUE TITLE
ObjectUpdatePacket should be split out into ~14 packets

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#38]
I've been reading the docs, and it strikes me that ObjectUpdatePacket is very unusual.

It's by far the largest and most complicated packet type, since it essentially covers 90% of what the server sends to clients. Like all other multiplexed packet types, it starts with a (depending on version) byte/int subtype code. The following data is then 100% dependent on the subtype.

I propose that ObjectUpdatePacket be split up into individual update packets, so UpdateAnomalyPacket, UpdateBasePacket, etc. (prefixed with Updated, so they are alphabetically close).

I'm not sure if the "Object Properties" should be merged into the "Packet Types" section (I think it would make sense), but at least I think the individual update packet types should be documented.

Would you accept a pull request for this?

**Comment by rjwut** [comment]
Actually, that's the way it used to be. It was changed to more accurately reflect the nature of these packets. The value that seems like a packet subtype is not that at all: it's a value indicating the type of the first object in the packet. You can tell because when multiple objects are stored in the packet, _the object type value is repeated for each one_. The "subtype" value belongs to the object itself, not the packet that transmits it, therefore the packet does not actually have subtypes. Listing it as a subtype is misleading because every other subtyped packet that contains an array does not repeat the subtype with each element.

The misconception is reinforced by the fact that the _Artemis_ server doesn't send `ObjectUpdatePacket`s with heterogeneous object types, even though the protocol actually supports it. But there is no reason that I'm aware of that would prevent _Artemis_ from doing that in the future, and in fact I would do exactly that if I were Thom because it would reduce the number of packets to be transmitted.

**Comment by chrivers** [comment]
Ah, I misread the docs then. I thought the field was not repeated. Perhaps the docs could be a little clearer on what part of the packet is repeated. Would you accept a PR for that?

**Comment by rjwut** [comment]
I agree that the `ObjectUpdatePacket` entry could be written to make this more clear. I'd welcome a pull request to improve this.
