### ISSUE TITLE
Creature is wrong

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#56]
Verified the following on 2.4:
1. Bit field is 3 bytes
2. The "creature type" is 32 bits (previously not specified)
3. There are 10 unknown 4-byte fields after creature_type_id. I think they make most sense as u32 for now.

I'll see if I can find the time to make some PRs for this (and the other recent issues)

**Comment by NoseyNick** [comment]
Confirmed, with caveats. As explained in #75, yes, a 16-bit bitfield is expected to take 3 bytes   :smile: 

The "10 unknown 4-byte fields" were only "6 unknown 4-byte fields" BEFORE 2.3.0. The bitfield was then 14 bits = 2 bytes (ff 3f fully-pop)

v2.3.0, they became "10 unknown 4-byte fields", for a 16-bit (3 byte) bitfield (fully-populated is ffff00).

Hoping to automate a fairly comprehensive audit of all protocol versions (or all the ones I have captures for), all objects, their bitfields, their field lengths, maybe types. Getting there   :smile:

**Comment by rjwut** [comment]
Can we determine some more of these fields? As described above, we actually lose the x, y, z, heading, pitch and roll properties, which are known in previous protocol versions and which clearly continue to exist in 2.4+.

**Comment by NoseyNick** [comment]
Hope this helps... Using my not-yet-completely-automated work-in-progress "marfez" reverse-engineering tool, and analysing over half a million Creature objectBitStream packets objects from 100 version 2.6 games, I can tell you...

3-byte bitmask,values up to ffff00 ("consistent" with 32 fields)

bit 1.1 float (from approx 1415 to 99991)
bit 1.2 float (-2865 .. 2893, frequently -50 .. 50 or even -10..10)
bit 1.3 float (161 .. 99495)
bit 1.4 str EG "CHARYBDIS", "NSECT", "WHALE", "WRECK" etc
Think we can still safely assume X,Y,Z,Name for the above?

bit 1.5 float (-pi to slightly more than +pi), lots of updates
bit 1.6 float (-0.15 .. 0.433, but ALMOST always REALLY close to 0?)
bit 1.7 float (0 .. 376.2), really low for "WRECK" (0.006, 0.0135, 0.0105)
Can we still assume Heading, Pitch, Roll? Oddly inconsistent units (radians, radians, deg, or what?) but plausible?

bit 1.8 u32 (1..7) - CreatureType, as documented. 1="WHALE", 5="CHARYBDIS", Turns to 7 when Name turns to "WRECK", so almost certainly.

bit 2.1 signed(?) int32 (Often values like 0, 4, 6, sometimes 2). Goes to -1 (0xffffffff) on "WRECK". I've also seen 0x40000000 which is just... B'zzarre, and 0x40000002 and 0x40000006 which are even more surreal. Wondering if it's some sort of 32-bit "flags" field?

bit 2.2 u32 (ALMOST always 0), except when it isn't, but damn it's going to be hard to track this one down. Wondering if it's another set of possibly-flags? The individual bytes I've seen values 0..67, 0..0, 0..55, 0..0. MIGHT be another case of "random bit of memory sometimes gets copied here"?

bit 2.3 float (0 .. 0.12), often "reeeeeally close to 0" floats like 2.94e-39, far more often real 00000000. It's totally plausible there's other "random memory" sneaking in here too and I'm misinterpreting them as "floats really close to 0"?

bit 2.4 float(0 .. 1). Pretty sure these are ACTUAL floats.
bit 2.5 float(0 .. 1)
bit 2.6 float(0 .. 1.5)
... and these 2 fields were added in v2.3.0 or thereabouts:
bit 2.7 float(-10 .. 400, occasionally 30000, frequently 1 or 20) (20 on "WRECK")
bit 2.8 float(1 .. 400, occasionally 30000) (20 on "WRECK")
The 400,400 are CHARYBDIS, I can't find the 30000s so easily.

I keep telling myself I need to learn mission-file-docs.txt in order to piece the actual MEANING of these fields together better. Whales and piranhas are supposed to have a "podnumber" 0-9 for example, but I can't see where the heck that would be hidden in ANY of the fields above.

Will make a note to play with mission-file-docs.txt to pin some of the types down a bit better.

**Comment by rjwut** [comment]
If there are ten unknown fields after the creature type, then there should be descriptions for bits 3.1 and 3.2. But above you only give descriptions through bit 2.8, and say that the fully-populated bit field is `ffff00`. Can you disambiguate?

**Comment by NoseyNick** [comment]
My latest Creature
```
0x0f => ['Creature',
        X=>Float, Y=>Float, Z=>Float, Name=>UTF16str,
        Heading=>Float, Pitch=>Float, Roll=>Float,
        CreatureType=>u32, # +++ should enumerate :-/
        Unknown21=>i32, # SIGNED int. -1, 0, 2, 4, 6 seen. "Scanned"?
        Unknown22=>u32,  # zero?
        # ALL these look wrong - ints? bitmasks? :
        Unknown23=>u32, Unknown24=>u32, Unknown25=>u32, Unknown26=>u32,
        $PROTOVERSION >= 2.3 ? (
            Health=>Float,    # <= 20, 30000, 400 - yeah honestly no health before 2.3.0?
            MaxHealth=>Float, # == 20, 30000, 400
        ) : (),
        $PROTOVERSION >= 2.6.3 ? ( Unknown31=>Byte ) : (), # Tag-related? 1 or 2?
    ],
```
... however I also admit it "needs work" and intend to learn mission-file-docs.txt to fill some gaps.

**Comment by NoseyNick** [comment]
I think the above updates would notably improve the doc, even if there's still a few "Unknowns".

**Comment by NoseyNick** [comment]
Object Type 0x0f Creature (was 0x0e before v2.1.5)
  X (bit 1.1, float)
  Y (bit 1.2, float)
  Z (bit 1.3, float)
  Name (bit 1.4, string)
  Heading (bit 1.5, float) (since v2.1.5)
  Pitch (bit 1.6, float) (since v2.1.5)
  Roll (bit 1.7, float) (since v2.1.5)
  CreatureType (bit 1.8, int) (since v2.1.5)
  Unknown (bit 2.1, int) (since v2.1.5) # "Scanned" bitmask?
  Unknown (bit 2.2, int) (since v2.1.5) # What "side" they are on, maybe?
  Unknown (bit 2.3, int) (since v2.1.5)
  Unknown (bit 2.4, int) (since v2.1.5)
  Unknown (bit 2.5, int) (since v2.1.5)
  Unknown (bit 2.6, int) (since v2.1.5)
  Health (bit 2.7, float) (since v2.3.0)
  MaxHealth (bit 2.8, float) (since v2.3.0)
  Unknown (bit 3.1, byte) (since v2.6.3) # Might be tag-related
  Unknown (bit 3.2, int) (since v2.7.0)
