### ISSUE TITLE
What licence does protocol-docs use?

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#64]
As far as I can tell, it's not specifically stated anywhere?

Are we talking CC, GPLv2/3, BSD, PD?

**Comment by rjwut** [comment]
We haven't specified one. Personally, I feel that we should be as open and free as possible with it. We **want** people to take this and run with it. Any suggestions?

**Comment by chrivers** [comment]
I strongly disfavor PD, since it just opens up a terrible can of worms.

I prefer GPLv2. What do you think of that?

As an fallback option, BSD with Attribution clause?

**Comment by mrfishie** [comment]
MIT is probably the most open one (although I don't particularly know a lot about the differences between licenses) - that's what I'd prefer, as it allows people to take this and pretty much do whatever, as long as they give attribution back to Artemis Nerds.

I'd prefer to not go with GPL due to the requirement that code that depends on something GPL-licensed also has to be GPL-licensed - this would prevent people including the project in closed-source projects (which especially becomes a problem when we start transferring to the structured format, although I'm not sure how the license works around using that data to create source code files).

**Comment by chrivers** [comment]
I'm perfectly on board with MIT+Attr for this :)

**Comment by mrfishie** [comment]
@rjwut @IvanSanchez Are you guys happy if we go with MIT for this?

**Comment by IvanSanchez** [comment]
@mrfishie I'm fine with MIT. Heck, I'm even fine with WTFPL.

**Comment by rjwut** [comment]
Is MIT appropriate for this, since it applies only to software? I know that some software is being written to support this, but the documentation itself isn't software. Also, we need to be very clear that the license applies to the **documentation** of the protocol, not the protocol itself.

**Comment by chrivers** [comment]
@rjwut very good points. I agree that it's important to clarify that the licence only applies to the protocol description.. 

but then again, what about the html, css and javascript? At least parts of those should be considered "software".

As far as I know, there's no problem using a licence intended for software, for a only-partially software project.

Alternatively, we can take a look here for a general selection:

http://choosealicense.com/licenses/

Or we could chose the simplest Creative Commons (CC) license:

https://creativecommons.org/choose/#metadata
https://creativecommons.org/licenses/by/4.0/

**Comment by mrfishie** [comment]
On the "Non-Software Licenses" page on Choose A License, it says this about documentation (which I believe includes what we're doing)

> **Documentation**
> _Any open source software license_ or open Creative Commons license is applicable to software documentation. If you use different licenses for your software and its documentation, you may wish to take care that source code examples in the documentation are also licensed under the software license.

(emphasis mine)

So I believe it should be okay to use MIT, but I do agree that we need to make it clear that it applies to the documentation.

I'm also alright with CC, but I think in the programming world (which is probably where the people using this would come from), the MIT license and what it stands for is arguably more well known.

**Comment by chrivers** [comment]
Personally, I think putting the MIT license on the entirety of the project (html, css and js) would work just fine.

If we decide on a way to auto-generate the documentation, it would be even easier to specify which part has which license. For example, here: https://github.com/chrivers/protocol-docs you can see current auto-generated version of the docs. The html file is much smaller, and pulls most of the "grunt" work from the STF protocol spec, but still contains some manual bits. Realistically, it always will, in the forms of examples, explanations, and so on.

But still, that would make it kind of easy to give the raw protocol spec one license, and a specific template/dependent project another - although I don't see the utility of doing that.

Maybe I don't understand what you mean by "documentation of the protocol, not the protocol itself", @rjwut. What we have right now, is the documentation. We can't copyright the abstract idea of the protocol as a platonic ideal.

..I feel almost certain I misunderstood something. Can someone help me clear up the confusion? :)

**Comment by rjwut** [comment]
@chrivers Well, what we are creating here is documentation, and since we're the creators of said documentation, we can apply whatever license to it we like. We didn't create the protocol itself, so we have no authority to apply any sort of license to that. What I want to avoid is someone thinking that _we_ created the protocol. That is Thom's baby and I don't want anyone to think that we believe otherwise. You and I understand there's a difference between the protocol and the documentation of that protocol, but that distinction may not be obvious to others, so I think it's better to err on the side of caution and make sure that our wording is unambiguous. Something like, "_Artemis_ and its various protocols were created by Thom Robertson. This unofficial documentation was created by the _Artemis_ player community and is released under the MIT license... etc."

**Comment by mrfishie** [comment]
Alright, I've created a pull request at #68 adding the licence and a small disclaimer in the readme. I've also put in a few questions we should probably decide on before pulling the change.

**Comment by chrivers** [comment]
@rjwut ah, yes that makes sense. We definitely want to avoid anyone thinking that we are trying to imply ownership. Completely agree

**Comment by mrfishie** [comment]
Closed with #68

**Comment by rjwut** [comment]
As I've merged the pull request applying the MIT license, I'm closing this issue. If there's a problem, comment and I'll re-open if needed.
