### ISSUE TITLE
Document changes in v2.2.0

### ISSUE THREAD

**Issue by IvanSanchez** [artemis-nerds/protocol-docs#9]
According to the forums, 2.2.0 is out. This means:
- [X] New monsters
  - [x] Investigate whether new packet, or reuses the "ZZ" monster packet
  - Whales and monsters are combined into a new creature object type. Wrecks are also considered creatures. Fields documented in the 5 July 2015 comment below.
  - [X] Investigate whether the space whale packet has changed to accommodate non-hostile monsters
  - See above
  - [X] Document the NSECT monster
  - Same as all other creatures
- [X] Anomalies are now "pickups"
  - [X] Investigate new fields
  - Documented in 5 July 2015 comment below
- [ ] Working upgrade system (apparently some consoles can "activate" the pickups/upgrades)
  - [ ] Investigate now the upgrades packet works
  - [ ] Investigate how to trigger abilities from clients
  - [ ] Check whether the popup when a pickup is picked up comes from the upgrades packets, or from a separate (and already known) game server message.
- [X] One new type of torpedo (plasma shock)
  - [X] One more enum
  - [X] Changes in the structure of the WeaponsUpdate packet

**Comment by IvanSanchez** [comment]
I spent quite some time with 2.2.0 and managed to see a lot of the changes already. Refer to https://github.com/artemis-nerds/node-asbs-lib/commit/6279eb5f844c05949b9385f9999360a38397d83b

**Comment by rjwut** [comment]
[Forum thread about various pickup and monster types](http://artemis.forumchitchat.com/post/spoiler-alert-list-of-all-pickups-in-2-2-7464525?pid=1287585464#post1287585464)

**Comment by dthaler** [comment]
The change in WeapPlayerUpdatePacket is as follows... the current doc page says
"Bit field (3 bytes)
This bit field indicates what field values are in this packet. This allows packets to be shorter by only including the values to be updated rather than all of them every time. If a bit is set to 1, that data value is included. (Each subsequent field indicates the bits in this bit field to which it corresponds.) 
Ordnance counts (bits 1.1-1.4, array)
This array contains up to four byte elements. Each element gives how many of a particular ordinance are stored on the ship, in the following order: homing missiles, nukes, mines, EMPs. 
Unknown (bit 1.5, byte)"

The changes are that
1) the bit field is now 4 bytes not 3 (so it's not backwards compatible).
2) A Pshock ordnance count bit was added before the "Unknown (bit 1.5, byte)", thus shifting all bits down by one
3) Also in the ordnance enumeration used for tube contents, an ordnance type of 0x4 means Pshock

**Comment by IvanSanchez** [comment]
Pickup types and monster types are noted in artemis-nerds/ArtemisMissionEditor#3

**Comment by rjwut** [comment]
@IvanSanchez I noticed that space whales now appear to be handled by the same packet as monsters, which says to me that object type `0x10` is probably for drones now rather than whales. We should try to confirm that.

**Comment by rjwut** [comment]
Some creatures I captured, trying to figure out fields; input is appreciated.

Bit | Data type | Purpose | Value | Bytes
--- | --- | --- | --- | ---
n/a | byte (enum) | object type | creature | `0f`
n/a | int | ID | 2348 | `2c090000`
n/a | bit field | bit field | 1001110100111100 | `9d3c`
1.1 | float? | coordinate? | 99987.97? | `fc49c347`
1.4 | float? | coordinate? | 97322.92? | `7615be47`
1.5 | string | name | CHARYBDIS | `0a000000 4300 4800 4100 5200 5900 4200 4400 4900 5300 0000`
1.6 | float? | ? | -0.30000007? | `9c9999be`
1.8 | int (enum) | creature type | charybdis | `05000000`
2.3 | ? | ? | ? | `2d002d00`
2.4 | ? | ? | ? | `20004200`
2.5 | ? | ? | ? | `52004100`
2.6 | ? | ? | ? | `73007300`

Bit | Data type | Purpose | Value | Bytes
--- | --- | --- | --- | ---
n/a | byte (enum) | object type | creature | `0f`
n/a | int | ID | 2349 | `2d090000`
n/a | bit field | bit field | 1001110100111100 | `9d3c`
1.1 | float? | coordinate? | 36714.74? | `bd6a0f47`
1.4 | float? | coordinate? | 32684.486? | `f958ff46`
1.5 | string | name | DRAGON | `07000000 4400 5200 4100 4700 4f00 4e00 0000`
1.6 | float? | ? | -0.99999934? | `f5ff7fbf`
1.8 | int (enum) | creature type | dragon | `03000000`
2.3 | ? | ? | ? | `0000c443`
2.4 | ? | ? | ? | `0000c443`
2.5 | ? | ? | ? | `0080dcc3`
2.6 | ? | ? | ? | `0000c4c3`

Bit | Data type | Purpose | Value | Bytes
--- | --- | --- | --- | ---
n/a | byte (enum) | object type | creature | `0f`
n/a | int | ID | 2350 | `2e090000`
n/a | bit field | bit field | 1011111100111100 | `bf3c`
1.1 | float? | coordinate? | 62979.16? | `29037647`
1.3 | float? | ? | 12.605776? | `42b14941`
1.4 | float? | coordinate? | 39086.03? | `08ae1847`
1.5 | string | name | NSECT | `06000000 4e00 5300 4500 4300 5400 0000`
1.6 | float? | ? | -0.99999934? | `f5ff7fbf`
1.7 | float? | ? | 1.837617E-8? | `a0d99d32`
1.8 | int (enum) | creature type | insect | `06000000`
2.3 | ? | ? | ? | `2d002d00`
2.4 | ? | ? | ? | `20004200`
2.5 | ? | ? | ? | `52004100`
2.6 | ? | ? | ? | `73007300`

**Comment by rjwut** [comment]
Okay, I have enough information on the creature and anomaly payloads that I can parse them without any exceptions: (I deleted my previous post because I had gotten the field order backwards and didn't want to create any confusion.)

Creatures:
- 1.1: X (float)
- 1.2: Y (float)
- 1.3: Z (float)
- 1.4: Name (string)
- 1.5: Heading (float)
- 1.6: Pitch (float)
- 1.7: Roll (float)
- 1.8: Creature type (int, enum)
- 2.1 - 2.6: Unknown (4 bytes each)

Anomalies:
- 1.1: X (float)
- 1.2: Y (float)
- 1.3: Z (float)
- 1.4: Upgrade (int, enum)

**Comment by rjwut** [comment]
Here's a packet that I captured that appears to provide the current upgrades available for your ship, and my best guess at how it breaks down:

`efbeadde` header
`9c000000` packet size
`01000000` from server
`00000000` padding
`88000000` remaining bytes
`f93d8080` packet type
`04` packet subtype
`41040000` ship ID?
`ff ff ff ff ff ff ff ff ff ff 0f` bit field
`00000000` upgrade 1
`00000000` upgrade 2
`00000000` upgrade 3
`00000000` upgrade 4
`00000000` upgrade 5
`00000000` upgrade 6
`00000000` upgrade 7
`00000000` upgrade 8
`00000000` upgrade 9
`00000000` upgrade 10
`00000000` upgrade 11
`00000000` upgrade 12
`00000000` upgrade 13
`00000000` upgrade 14
`00000000` upgrade 15
`00000000` upgrade 16
`00000000` upgrade 17
`00000000` upgrade 18
`00000000` upgrade 19
`00000000` upgrade 20
`00000000` upgrade 21
`00000000` upgrade 22
`00000000` upgrade 23
`00000000` upgrade 24
`00000000` upgrade 25
`00000000` upgrade 26
`00000000` upgrade 27
`00000000` upgrade 28
`00000000` upgrade 29

Each upgrade field is presumably how many of that upgrade you have; I need to capture some more when I've picked some up to confirm. The bit field is confusing to me, since it seems to have enough bits for 84 fields, when there seem to only be 29.

**Comment by rjwut** [comment]
Most of this is documented now. I've also refactored the documentation to have just one ObjectUpdatePacket with different structures for the various object types instead of separate packet types. This has reduced how much repeated verbiage there is, as now there is one place to explain how world object update packets function.

**Comment by rjwut** [comment]
Speaking of which, I've finally realized why we get the `0x80803df9`:`0x00` packets! We've noted previously that every object update packet contains only one object type. What the game is doing is iterating over the object types and producing update packets for them. If there are no updates for a particular object type, you get an object update packet with no entries in it, so the payload just contains `0x00`. That's why you get more of those empty packets when you turn off anomalies, space monsters, etc.

**Comment by dthaler** [comment]
Regarding, in the Comms packets:
"Priority (int)
    Values appear to range from 0x00 (high priority) to 0x08 (low priority). In the stock client, this affects the message's background color."

Is there any reason this needs to be called "priority"?  Based on observations of what messages actually appear with which values, I'm not sure that the numbers are actually in order by priority.  For example "docking complete" is sent on 0x04 is not really higher priority than accepting a docking request (0x05) or a notice of "transfer complete" (0x07).   Another example is that a base under direct attack (0x04) is not really lower priority than a taunt coming in from an enemy (0x00).  Can we call this number the "channel" instead of "priority"?

**Comment by UserMcUser** [comment]
If the only real effect of the value is to set the background color of a message, why not call it "BackgroundColor" or something similar?

**Comment by rjwut** [comment]
What you guys are talking about is a separate issue from this one. I will create one for it.

**Comment by NoseyNick** [comment]
Player Ship Upgrades object appears to be...
[ see own issue: PlayerShipUpgradePacket details #18 ]

**Comment by NoseyNick** [comment]
Same pattern with Unknown21 vs SecretCodeCase5_5 vs Unknown91, yup, I'm pretty convinced, we have 28 bytes for upgrades "in use", 28 bytes for upgrade "quantities", 28 shorts for upgrade countdowns whilst in use, total 84 bits of the 11-byte bitfield.

**Comment by rjwut** [comment]
Interesting. I'll do some experiments of my own as well.

**Comment by NoseyNick** [comment]
The array of ANY objects in the ObjectUpdatePacket also appears to be terminated by a 4-byte "\0\0\0\0" (or an int 0 if you prefer). If it doesn't end like that, but with a different number of 0 bytes, you probably have the wrong length for some other field in your object (in fact this is how I decided the last 28 fields are probably supposed to be 2-byte shorts in the Upgrades object)

This feels slightly awkward considering we are expecting an ObjectType BYTE in your ObjectUpdatePacket, but may be an artefact left over from when ObjectType used to be an Int? Compare / contrast the EngGridUpdatePacket, where you're expecting an X-coord BYTE, or terminating FF BYTE, or a TeamID BYTE, or terminating 0xfe BYTE. In ObjectUpdatePacket you're looking out for an ObjectType BYTE (followed by a 4-byte int ID), or a terminating FOUR-BYTE 0x00000000   <shrug />

I'm working on some Perl to parse Artemis protocols, if anyone cares. Hey, we have Java, NodeJS, and DotNet, why not Perl too?   :laughing:

**Comment by rjwut** [comment]
That was pretty much the whole point of documentation project: we want to encourage people to develop Artemis network libraries in other languages! I don't write Perl, but I'm glad you're working on it!

**Comment by NoseyNick** [comment]
KeyCaptureTogglePacket Type: 0xf754c8fe:0x11 [from server]
Subtype (byte) Always 0x11, Capture (boolean, 4 bytes)
... seems to have become Subtype(**int**) Always 0x11, Capture (**boolean, 1 byte**)

Is this the right place to be posting corrections BTW, and/or should I be making separate issues, or even working out how to submit diffs / pull-reqs or something?

**Comment by dthaler** [comment]
Just in case you're keeping track of Artemis network libraries in other languages, I have one in C++ that is used by Artemis DMX Tools.   This documentation project has been extremely valuable.

**Comment by NoseyNick** [comment]
I have packet captures with a bunch of undocumented packet 0xf754c8fe subtype 0x13 (int usuallySeven, int objID). Seems to happen immediately before DestroyObject(Mine, objID) or DestroyObject(Torpedo, objID). I'm not sure what "usuallySeven" is except that it's usually 0x07. Does NOT seem to correspond to ObjectType 'cos it's 0x07 for both Mines or Torpedos. Will see if I can recreate sometime. In the meantime I am calling it UnknownMaybeDetonatePacket. Anyone have better details?

**Comment by NoseyNick** [comment]
I have seen 18 instances in 2 games of undocumented packet 0x4c821d3c subtype 0x05, payload 4 bytes, all zeroes, No idea if that's a 0 int, float, boolean, or enumerated something.   :-(

**Comment by NoseyNick** [comment]
I have seen a few (very few) ClimbDivePacket Type: 0x4c821d3c:0x1b but Direction (int) is 5, 6, or 8, NOT +1 / -1. Will try to recreate, unless anyone has better details?

**Comment by mrfishie** [comment]
> @NoseyNick
> Is this the right place to be posting corrections BTW, and/or should I be making separate issues, or even working out how to submit diffs / pull-reqs or something?

Separate issues would be good, pull requests would be even better :smile:

**Comment by rjwut** [comment]
Yes, for each distinct correction to the documentation, please file a separate issue.
